#!/usr/bin/env bash

set -eo pipefail

sudo -v
while true; do sleep 60; sudo -n true; kill -0 "$$" || exit; done 2>/dev/null &

SETUP_DIRECTORY=$(realpath "$(dirname "$0")")

sudo cp -rf etc/* /etc

localectl set-keymap de
localectl set-locale en_US.UTF-8
timedatectl set-timezone Europe/Berlin

if ! command -v paru &> /dev/null; then
    cd "$(mktemp -d)" && git clone https://aur.archlinux.org/paru-bin.git . && makepkg -sim --noconfirm && cd -
fi

paru -Sy --nosudoloop --needed --noconfirm - < "$SETUP_DIRECTORY/packages"

sudo usermod -aG docker,video "$USER"
sudo systemctl enable bluetooth docker fstrim.timer systemd-timesyncd greetd

xdg-user-dirs-update && mkdir -p ~/Pictures/screenshots ~/Videos/recordings

GPG_TTY="$(tty)"
export GPG_TTY

SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
export SSH_AUTH_SOCK

sudo find ~/.gnupg -type d -exec chmod 700 {} \;
sudo find ~/.gnupg -type f -exec chmod 600 {} \;

paru -Sy --nosudoloop --needed --noconfirm \
    browserpass-chromium \
    browserpass-firefox \
    ccid \
    gnome-keyring \
    openssh \
    pam-u2f \
    pass \
    pcsclite \
    polkit \
    polkit-gnome \
    yubico-authenticator-bin

sudo systemctl enable --now pcscd

GPG_KEY="A00155F3C961D57E645299D66BEB117F7BDBD749"
gpg --recv-keys "$GPG_KEY"
echo "$GPG_KEY:6:" | gpg --import-ownertrust
gpg --card-status

export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

git -C ~ remote set-url origin git@github.com:phisch/dotfiles.git
git clone git@github.com:phisch/passwords.git ~/.password-store
