#!/usr/bin/env bash

bspc subscribe node_state | while read -r _ _ _ node state status; do
    echo $node $state $status
    if [[ "$state" == "floating" ]]; then
        case "$status" in
            off) xprop -id "$node" -remove _WM_STATE_FLOATING;;
            on) xprop -id "$node" -f _WM_STATE_FLOATING 32c -set _WM_STATE_FLOATING 1;;
        esac
    fi
done