"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$all"

[directory]
style = "yellow"

[line_break]
disabled = true

[character]
success_symbol = "[❯](bold white)"

[git_branch]
symbol = " "
style = "#555555"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold #555555"

untracked = "[u](red)"
stashed = "[󰏗 ](yellow)"
modified = "[m](yellow)"

staged = "[s](green)"
renamed = "[r](blue)"
deleted = "[d](red)"
