#!/usr/bin/env zsh
bspc monitor DP-0 -d 1 2 3 4
bspc monitor DP-2 -d 5 6 7 8

bspc config border_width 0
bspc config window_gap 5
bspc config top_padding -5
bspc config right_padding -5
bspc config bottom_padding -5
bspc config left_padding -5
bspc config split_ratio 0.5
bspc config focus_follows_pointer false
bspc config pointer_follows_monitor false
bspc config click_to_focus any
bspc config remove_disabled_monitors true
bspc config presel_feedback_color "#8F5CD6"
bspc config external_rules_command ~/.config/bspwm/external_rules
bspc config pointer_motion_interval 7

bspc rule -a Qemu-system-x86_64 state=floating monitor=^1 rectangle=800x628+1700+762
bspc rule -a Toolbox state=tiled

wmname LG3D

~/.config/bspwm/subscriber/floating_state &

polybar `hostname` &

compton --experimental-backends &
sxhkd &
