#!/usr/bin/env zsh
bspc monitor DP-0 -d 1 2 3 4
bspc monitor DP-2 -d 5 6 7 8
bspc monitor DP-4 -d 9 10 11 12

#bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 0
bspc config window_gap 8

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer false
bspc config pointer_follows_monitor false
bspc config click_to_focus true

bspc rule -a Peek state=floating

wmname LG3D

polybar main -r &
#polybar laptop -r &

compton --config ~/.config/compton/compton.conf &
sxhkd &
