#!/usr/bin/env bash

wmname LG3D

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

xrandr --output DP-0 --mode 2560x1440 --rate 144.00 --rotate normal --pos 0x0
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
echo "Xcursor.size: 32" | xrdb -merge
xsetroot -cursor_name left_ptr

feh --randomize --bg-fill --recursive --no-fehbg ~/Pictures/wallpapers/*

bspc config border_width 0
bspc config window_gap 8
bspc config top_padding -8
bspc config right_padding -8
bspc config bottom_padding -8
bspc config left_padding -8
bspc config split_ratio 0.5
bspc config focus_follows_pointer false
bspc config pointer_follows_monitor false
bspc config click_to_focus any
bspc config presel_feedback_color "#6940E3"
bspc config external_rules_command ~/.config/bspwm/external_rules
bspc config pointer_motion_interval 16

bspc rule -a Toolbox state=tiled
bspc rule -a java-lang-Thread state=floating

~/.config/bspwm/subscriber/state_hint &

bspc config -m primary top_padding 0 && pkill -USR1 polybar || polybar -r "$HOSTNAME" &

picom -b
SXHKD_SHELL=bash sxhkd &
